name: Terragrunt apply
description: terragrunt apply
inputs:
  aws_profile:
    required: true
  target_dir:
    description: 'TARGET DIR'
    required: true
  git_ssh_command:
    description: "GIT SSH COMMAND"
    required: true
  working_directory:
    description: 'WORKING DIRECTORY'
    required: true
  tf_workspace:
    description: "TF WORKSPACE"
    required: true
  apply_url:
    description: "Pull request url"
    required: false
  base_ref:
    required: true
  head_ref:
    required: true
  refresh:
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - id: apply
      if: ${{ inputs.refresh == 'false' }}
      run:  ./deploy-terragrunt.sh apply "${TARGET_DIR}" 1> stdout.log 2> stderr.log
      continue-on-error: true
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      env:
        AWS_PROFILE: ${{ inputs.aws_profile }}
        TARGET_DIR: ${{ inputs.target_dir }}
        GIT_SSH_COMMAND: ${{ inputs.git_ssh_command }} 
        TF_WORKSPACE: ${{ inputs.tf_workspace }}

    - if: ${{ inputs.refresh == 'false' }}
      run: |
        if [ "${{ steps.apply.outcome }}" == "success" ]; then
          echo "# :heavy_check_mark:Terragrunt apply" > APPLY.md
          echo '```hcl' >> APPLY.md
          cat stderr.log | sed -n -e '/^Group/p' -e '/- Module/p' >> APPLY.md
          echo "" >> APPLY.md
          cat stdout.log | sed -n -e '/^Apply/p' >> APPLY.md
          echo '```' >> APPLY.md
          echo "<details>" >> APPLY.md
          echo "<summary>Details</summary>" >> APPLY.md
          echo -e "\n" >> APPLY.md
          echo '```hcl' >> APPLY.md
          cat stderr.log | sed -n -e '/^Group/p' -e '/- Module/p' >> APPLY.md
          echo "" >> APPLY.md
          cat stdout.log | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" >> APPLY.md
          echo '```' >> APPLY.md
          echo "</details>" >> APPLY.md

          echo -n "<!-- apply -->" >> APPLY.md
        else
          echo "# :bangbang:Terragrunt apply" > APPLY.md
          echo '```hcl' >> APPLY.md
          cat stderr.log | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" | sed -n -e '/^Error/,+4p' >> APPLY.md
          echo '```' >> APPLY.md
          echo "<details>" >> APPLY.md
          echo "<summary>Details</summary>" >> APPLY.md
          echo -e "\n" >> APPLY.md
          echo '```hcl' >> APPLY.md
          cat stderr.log | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" >> APPLY.md
          echo '```' >> APPLY.md
          echo "</details>" >> APPLY.md
          echo -n "<!-- apply -->" >> APPLY.md
        fi

        if [ -n "${APPLY_URL}" ]; then
          gh api --method PATCH -H "Accept: application/vnd.github+json" ${APPLY_URL} -f body="$(cat ./APPLY.md)"
        else
          gh pr comment ${PR_NUMBER} -F ./APPLY.md
        fi

      working-directory: ${{ inputs.working_directory }}
      shell: bash
      env:
        AWS_PROFILE: ${{ inputs.aws_profile }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        APPLY_URL: ${{ inputs.apply_url }}

    - if: ${{ steps.apply.outcome == 'failure' }}
      run: |
        result=$(gh issue create --title "Error terragrunt apply" -F ./APPLY.md --label "bug" )
        issue_num=$(echo $result | awk -F "/" '{ print $NF }')
        exit 1
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        BASE_REF: ${{ inputs.base_ref }}
        HEAD_REF: ${{ inputs.base_ref }}

    - id: refresh
      if: ${{ inputs.refresh == 'true' }}
      run:  ./deploy-terragrunt.sh 'apply -refresh-only' "${TARGET_DIR}" &>/dev/null
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      env:
        AWS_PROFILE: ${{ inputs.aws_profile }}
        TARGET_DIR: ${{ inputs.target_dir }}
        GIT_SSH_COMMAND: ${{ inputs.git_ssh_command }} 
        TF_WORKSPACE: ${{ inputs.tf_workspace }}

    - id: output
      if: ${{ steps.apply.outcome == 'success'  || steps.refresh.outcome == 'success' }}
      run: |
        set -x
        mkdir _output
        ls ./hcl | while read line; do
          terragrunt output --terragrunt-working-dir ./hcl/${line} >> _output/${line}
        done
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        AWS_PROFILE: ${{ inputs.aws_profile }}
        GIT_SSH_COMMAND: ${{ inputs.git_ssh_command }} 
        TF_WORKSPACE: ${{ inputs.tf_workspace }}


    - if: ${{ steps.output.outcome == 'success' }}
      run: |
        set -x 
        echo "# ${WORKING_DIR#./terraform/} Parameters" > OUTPUT.md
        ls _output | while read line; do
          echo "<details>" >> OUTPUT.md
          echo "<summary>${line}</summary>" >> OUTPUT.md
          echo -e "\n" >> OUTPUT.md
          echo '```hcl' >> OUTPUT.md
          cat _output/${line} | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"  >> OUTPUT.md
          echo '```' >> OUTPUT.md
          echo "</details>" >> OUTPUT.md
        done

        issue=$(gh issue list --json title,url | jq ".[] | select(.title == \"[${BASE_REF}]${WORKING_DIR#./terraform/} Parameters\")")
        if [ -n "${issue}" ]; then
          url=$(echo "${issue}" | jq -r .url)
          gh issue edit ${url} -F OUTPUT.md
        else
          gh issue create --title "[${BASE_REF}]${WORKING_DIR#./terraform/} Parameters" -F ./OUTPUT.md --label "documentation" 
        fi
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        WORKING_DIR: ${{ inputs.working_directory }}
        BASE_REF: ${{ inputs.base_ref }}