name: Read pull requests
description: Read pull requests
inputs:
  bot_name:
    required: false
    default: tf-action[bot]
outputs:
  init_url: 
    value: ${{ steps.read-pr.outputs.init_url }}
  plan_url:
    value: ${{ steps.read-pr.outputs.plan_url }}
  apply_url: 
    value: ${{ steps.read-pr.outputs.apply_url }}
  target_dir: 
    value: ${{ steps.read-pr.outputs.target_dir }}

runs:
  using: "composite"
  steps:
    - id: read_pr
      run: bash ${{ github.action_path }}/main.sh
      shell: bash
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        BOT_NAME: ${{ inputs.bot_name }}
        GITHUB_REPOSITORY: ${{ github.repository }}