name: Split branch
description: Split branch
inputs:
  github_action_token:
    required: true
  base_ref:
    required: true
  head_ref:
    required: true
  target_dir:
    required: false
    default: tmp
  terraform_base_dir:
    required: false
    default: terraform
outputs:
  is_commit: 
    value: ${{ steps.split_branch.outputs.commit }}

runs:
  using: "composite"
  steps:
    - run: | 
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git fetch --all
      shell: bash

    - id: split_branch
      run: bash ${{ github.action_path }}/main.sh 
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_action_token }}
        TARGET_DIR: ${{ inputs.target_dir }}
        TERRAFORM_BASE_DIR: ${{ inputs.terraform_base_dir }}
        BASE_REF: ${{ inputs.base_ref }}
        HEAD_REF: ${{ inputs.head_ref }}

    - if: ${{ steps.split_branch.outcome == 'success' && steps.split_branch.outputs.commit == 'true' }}
      run: |
        if [ ! -n "$(gh pr list --base ${BASE_REF} --head pr/${BASE_REF}/${HEAD_REF#feature/}_${TARGET_DIR} )" ]; then
          gh pr create --base ${BASE_REF} --head pr/${BASE_REF}/${HEAD_REF#feature/}_${TARGET_DIR} --title "pr/${BASE_REF}/${HEAD_REF#feature/}_${TARGET_DIR} -> ${BASE_REF}" --body ""
        fi
      shell: bash
      env:
        TERRAFORM_BASE_DIR: ${{ inputs.terraform_base_dir }}
        GITHUB_TOKEN: ${{ inputs.github_action_token }}
        TARGET_DIR: ${{ inputs.target_dir }}
        BASE_REF: ${{ inputs.base_ref }}
        HEAD_REF: ${{ inputs.head_ref }}