---
name: Push Feature Branch
on:
  push:
    branches:
      - 'feature/**'

permissions: write-all
env:
  BASE_REF: staging
  TERRAFORM_BASE_DIR: terraform
jobs:
  partial_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v3      
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - uses: ./.github/actions/split-branch
        with:
          base_ref: ${{ env.BASE_REF }}
          head_ref: ${{ github.ref_name }}
          github_action_token: ${{ steps.generate_token.outputs.token }}

  check_changes:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.check-deploy-accounts.outputs.dir }}
    steps:
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - id: check-deploy-accounts
        uses: ./.github/actions/check-deploy-accounts
        with:
          BASE_REF: ${{ env.BASE_REF }}
          github_action_token: ${{ steps.generate_token.outputs.token }}

  create_pr:
    needs: check_changes
    runs-on: ubuntu-latest
    if: ${{ needs.check_changes.outputs.dir != '[]' && needs.check_changes.outputs.dir != '' }}
    strategy:
      fail-fast: false 
      matrix:
        dir: ${{ fromJson(needs.check_changes.outputs.dir) }}
    steps:
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0

      - uses: ./.github/actions/split-branch
        with:
          base_ref: ${{ env.BASE_REF }}
          head_ref: ${{ github.ref_name }}
          target_dir: ${{ matrix.dir }}
          github_action_token: ${{ steps.generate_token.outputs.token }}
