---
name: Push Feature Branch
on:
  push:
    branches:
      - 'feature/**'

permissions: write-all
env:
  BASE_REF: staging
  TERRAFORM_BASE_DIR: terraform
jobs:
  generate_token:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.generate_token.outputs.token }}
    steps:
    - uses: actions/checkout@v3
    - id: generate_token
      uses: ./.github/actions/generate-github-app-token
      with:
        app_id: ${{ secrets.app_id }}
        installation_id: ${{ secrets.installation_id }}
        private_key: ${{ secrets.private_key }}

  partial_merge:
    runs-on: ubuntu-latest
    needs: generate_token
    steps:
      - uses: actions/checkout@v3      
        with:
          fetch-depth: 0
          token: ${{ needs.generate_token.outputs.token }}

      - uses: ./.github/actions/split-branch
        with:
          base_ref: ${{ env.BASE_REF }}
          head_ref: ${{ github.ref_name }}
          github_action_token: ${{ needs.generate_token.outputs.token }}

  check_changes:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.check-deploy-accounts.outputs.dir }}
    steps:
      - uses: actions/checkout@v3
      - id: check-deploy-accounts
        uses: ./.github/actions/check-deploy-accounts
        with:
          BASE_REF: ${{ env.BASE_REF }}

  create_pr:
    needs: [check_changes,generate_token]
    runs-on: ubuntu-latest
    if: ${{ needs.check_changes.outputs.dir != '[]' && needs.check_changes.outputs.dir != '' }}
    strategy:
      fail-fast: false 
      matrix:
        dir: ${{ fromJson(needs.check_changes.outputs.dir) }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ needs.generate_token.outputs.token }}
          fetch-depth: 0

      - uses: ./.github/actions/split-branch
        with:
          base_ref: ${{ env.BASE_REF }}
          head_ref: ${{ github.ref_name }}
          target_dir: ${{ matrix.dir }}
          github_action_token: ${{ needs.generate_token.outputs.token }}
