---
name: Push Feature Branch
on:
  push:
    branches:
      - 'feature/**'
      - 'renovate/**'

permissions: write-all
env:
  BASE_REF: staging
  TERRAFORM_BASE_DIR: terraform
  REPOSITORY: ${{ github.repository }}
jobs:
  get-changes:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.check-deploy-accounts.outputs.dir }}
    steps:
      - uses: actions/checkout@v3
      - id: check-deploy-accounts
        uses: ./.github/actions/check-deploy-accounts
        with:
          BASE_REF: ${{ env.BASE_REF }}

  create-pr-for-terraform:
    needs: get-changes
    runs-on: ubuntu-latest
    if: ${{ needs.get-changes.outputs.dir != '[]' && needs.get-changes.outputs.dir != '' }}
    strategy:
      fail-fast: false 
      matrix:
        dir: ${{ fromJson(needs.get-changes.outputs.dir) }}
    steps:
      - id: generate_token
        uses: ezqy/ghaction/generate-github-app-token@v0.0.1
        with:
          app_id: ${{ secrets.app_id }}
          installation_id: ${{ secrets.installation_id }}
          private_key: ${{ secrets.private_key }}

      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0

      - uses: ./.github/actions/split-branch
        with:
          base_ref: ${{ env.BASE_REF }}
          head_ref: ${{ github.ref_name }}
          target_dir: ${{ matrix.dir }}
          github_action_token: ${{ steps.generate_token.outputs.token }}

  create-pr-for-auto-merge:
    needs: get-changes
    runs-on: ubuntu-latest
    if: ${{ needs.get-changes.outputs.dir == '[]' || needs.get-changes.outputs.dir == '' }}
    steps:
      - id: generate_token
        uses: ezqy/ghaction/generate-github-app-token@v0.0.1
        with:
          app_id: ${{ secrets.app_id }}
          installation_id: ${{ secrets.installation_id }}
          private_key: ${{ secrets.private_key }}

      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0
      
      - uses: ./.github/actions/create-pr
        with:
          base_ref: ${{ env.BASE_REF }}
          head_ref: ${{ github.ref_name }}
          github_action_token: ${{ steps.generate_token.outputs.token }}