name: test

on:
  workflow_dispatch:

jobs:
  action_test:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/generate-github-app-token
      with:
        app_id: ${{ secrets.app_id }}
        installation_id: ${{ secrets.installation_id }}
        private_key: ${{ secrets.private_key }}
